common: 
  PGHOST: 'postgres-cont'
  upload_file_name: 'data.csv'
  upload_directory: './upload'
#  upload_type: 'allcolumns'
efficient_frontier:
  points_number: 30
  default_riskfree: 0.04
  default_datasource: 'morningstar'
  override_datasource: true
downloader_morningstar:
  datasource:   'morningstar'
  symbolColumn: 'Symbol'
  dateColumn:   'Date'
  priceColumn:  'Close'
  directory:    'downloads'

#TIINGO
downloader_:
  datasource:   'tiingo'
  symbolColumn: 'symbol'
  dateColumn:   'date'
  priceColumn:  'adjClose'
  directory:    'downloads'
  access_key:   'b52aff4cd1d604991702bf6bec5151924323ac4a'
#QUANDL
downloader_:
  datasource:   'quandl'
  symbolColumn: 'symbol'
  dateColumn:   'date'
  priceColumn:  'adjClose'
  directory:    'downloads'
  access_key:   'KtxeUhoJZDsmvsmhVsWf'
downloader_:
  datasource:   'marketdata'
  symbolColumn: 'symbol'
  dateColumn:   'date'
  priceColumn:  'adjClose'
  directory:    'downloads'
  access_key:   ''
downloader_:
  datasource:   'converter_invest'
  symbolColumn: 'symbol'
  dateColumn:   'date'
  priceColumn:  'close'
  directory:    'downloads'
  inputfilename: 'upload/b.txt'
  access_key:   ''
downloader:
  datasource:   'converter_asxhist'
  maxSparseness:  0.40
  symbolColumn: 'symbol'
  dateColumn:   'date'
  dateFormat:   '%Y%m%d'
  priceColumn:  'close'
  directory:    'downloads'
  inputfilename: 'upload/a.txt'
  access_key:   ''
