common: 
  PGHOST: 'postgres-cont'
  upload_file_name: 'data.csv'
  upload_directory: './upload'
#  upload_type: 'allcolumns'
efficient_frontier:
  points_number: 30
  default_riskfree: 0.04
  default_datasource: 'morningstar'
  override_datasource: true
downloader_morningstar:
  datasource:   'morningstar'
  symbolColumn: 'Symbol'
  dateColumn:   'Date'
  priceColumn:  'Close'
  directory:    'downloads'

downloader:
#  activesource:   'converter_asxhist'
  activesource:   'converter_invest'

downloaders:
  quandl:
    datasource:   'quandl'
    symbolColumn: 'symbol'
    dateColumn:   'date'
    priceColumn:  'adjClose'
    directory:    'downloads'
    access_key:   'KtxeUhoJZDsmvsmhVsWf'
  marketdata:
    datasource:   'marketdata'
    symbolColumn: 'symbol'
    dateColumn:   'date'
    priceColumn:  'adjClose'
    directory:    'downloads'
    access_key:   ''
  converter_invest:
    datasource:   'converter_invest'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%b %d, %Y'
    priceColumn:  'close'
    directory:    'downloads'
    inputfilename: 'upload/b.txt'
    access_key:   ''
  converter_asxhist:
    datasource:   'converter_asxhist'
    maxSparseness:  0.05
    symbolColumn: 'symbol'
    dateColumn:   'date'
    dateFormat:   '%Y%m%d'
    priceColumn:  'close'
    directory:    'downloads'
    inputfilename: 'upload/a.txt'
    access_key:   ''
